name: ML Run

on:
  push:
jobs:
    ml_run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4 #checkout means cloning.
        
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requirements.txt